ÍNDICE  
    1. OBTENCIÓN  
    1.1 LIMPIEZA  
    1.2 REPARACIÓN      
    2. DATOS FALTANTES   
    2.1 DISTRIBUCIÓN Y COMPORTAMIENTO DE LOS DATOS   
    3. GUARDAMOS PARA COMENZAR A TRABAJAR

# <CENTER> 1. OBTENCIÓN   
Fecha 22/11/2023
* Webscraping a través de extensión para navegador web (Web scraper) en la web: https://socialbook.io/instagram-channel-rank/top-200-instagrammers

## 1.1 Limpieza

In [2]:
#Importación de bibliotecas
import pandas as pd
import numpy as np

In [3]:
#Carga de datos
df = pd.read_csv('dataV1.csv')

In [4]:
# Exploración inicial
print(df.head())

  web-scraper-order                              web-scraper-start-url  \
0    1700689302-202  https://socialbook.io/instagram-channel-rank/t...
1    1700689302-203  https://socialbook.io/instagram-channel-rank/t...
2    1700689302-204  https://socialbook.io/instagram-channel-rank/t...
3    1700689302-205  https://socialbook.io/instagram-channel-rank/t...
4    1700689302-206  https://socialbook.io/instagram-channel-rank/t...

       Channel Info  Influence Score Followers Avg_Likes Posts  \
0               NaN              NaN       NaN       NaN   NaN
1    1cristianoFree             92.0    612.6m      8.9m  3.6k
2     2leomessiFree             90.0    493.1m      7.6m  1.1k
3  3selenagomezFree             93.0    430.1m      6.7m  2.0k
4  4kyliejennerFree             91.0    398.9m      8.0m  6.9k

  60-Day Eng Rate New Post Avg_Likes Total Likes Country Or Region
0             NaN                NaN         NaN               NaN
1            1.1%               6.5m       31.7b             Spain
2            1.0%               4.6m        8.7b               NaN
3            1.0%               4.1m       13.1b     United States
4            0.7%               2.9m       54.9b     United States

In [5]:
#primer vistazo
df.head()

,web-scraper-order,web-scraper-start-url,Channel Info,Influence Score,Followers,Avg_Likes,Posts,60-Day Eng Rate,New Post Avg_Likes,Total Likes,Country Or Region
0,1700689302-202,https://socialbook.io/instagram-channel-rank/t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1700689302-203,https://socialbook.io/instagram-channel-rank/t...,1cristianoFree,92.0,612.6m,8.9m,3.6k,1.1%,6.5m,31.7b,Spain
2,1700689302-204,https://socialbook.io/instagram-channel-rank/t...,2leomessiFree,90.0,493.1m,7.6m,1.1k,1.0%,4.6m,8.7b,NaN
3,1700689302-205,https://socialbook.io/instagram-channel-rank/t...,3selenagomezFree,93.0,430.1m,6.7m,2.0k,1.0%,4.1m,13.1b,United States
4,1700689302-206,https://socialbook.io/instagram-channel-rank/t...,4kyliejennerFree,91.0,398.9m,8.0m,6.9k,0.7%,2.9m,54.9b,United States

In [6]:
# elimina columnas web-scraper-order y web-scraper-start-url
df.drop(['web-scraper-order', 'web-scraper-start-url'], axis=1, inplace=True)
df

,Channel Info,Influence Score,Followers,Avg_Likes,Posts,60-Day Eng Rate,New Post Avg_Likes,Total Likes,Country Or Region
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1cristianoFree,92.0,612.6m,8.9m,3.6k,1.1%,6.5m,31.7b,Spain
2,2leomessiFree,90.0,493.1m,7.6m,1.1k,1.0%,4.6m,8.7b,NaN
3,3selenagomezFree,93.0,430.1m,6.7m,2.0k,1.0%,4.1m,13.1b,United States
4,4kyliejennerFree,91.0,398.9m,8.0m,6.9k,0.7%,2.9m,54.9b,United States
...,...,...,...,...,...,...,...,...,...
196,196frenchmontana,72.0,37.5m,138.2k,160,0.4%,148.9k,22.1m,United States
197,197bmw,79.0,37.5m,213.4k,10.0k,0.3%,104.2k,2.1b,Germany
198,198madhuridixitnene,76.0,37.2m,369.7k,1.6k,0.6%,227.2k,593.7m,India
199,199addisonraee,85.0,36.8m,2.8m,165,1.1%,382.8k,464.0m,NaN
200,200shaymitchell,83.0,36.7m,613.2k,6.5k,0.6%,214.7k,4.0b,United States

In [7]:
# elimina fila posición 0
df.drop(0, axis=0, inplace=True)
df

,Channel Info,Influence Score,Followers,Avg_Likes,Posts,60-Day Eng Rate,New Post Avg_Likes,Total Likes,Country Or Region
1,1cristianoFree,92.0,612.6m,8.9m,3.6k,1.1%,6.5m,31.7b,Spain
2,2leomessiFree,90.0,493.1m,7.6m,1.1k,1.0%,4.6m,8.7b,NaN
3,3selenagomezFree,93.0,430.1m,6.7m,2.0k,1.0%,4.1m,13.1b,United States
4,4kyliejennerFree,91.0,398.9m,8.0m,6.9k,0.7%,2.9m,54.9b,United States
5,5therock,91.0,392.8m,1.7m,7.5k,0.3%,982.9k,12.5b,United States
...,...,...,...,...,...,...,...,...,...
196,196frenchmontana,72.0,37.5m,138.2k,160,0.4%,148.9k,22.1m,United States
197,197bmw,79.0,37.5m,213.4k,10.0k,0.3%,104.2k,2.1b,Germany
198,198madhuridixitnene,76.0,37.2m,369.7k,1.6k,0.6%,227.2k,593.7m,India
199,199addisonraee,85.0,36.8m,2.8m,165,1.1%,382.8k,464.0m,NaN
200,200shaymitchell,83.0,36.7m,613.2k,6.5k,0.6%,214.7k,4.0b,United States

## 1.2 REPARACIÓN

In [8]:
# elimina la palabra Free de la columna Channel Info
df['Channel Info'] = df['Channel Info'].str.replace('Free', '')
df

,Channel Info,Influence Score,Followers,Avg_Likes,Posts,60-Day Eng Rate,New Post Avg_Likes,Total Likes,Country Or Region
1,1cristiano,92.0,612.6m,8.9m,3.6k,1.1%,6.5m,31.7b,Spain
2,2leomessi,90.0,493.1m,7.6m,1.1k,1.0%,4.6m,8.7b,NaN
3,3selenagomez,93.0,430.1m,6.7m,2.0k,1.0%,4.1m,13.1b,United States
4,4kyliejenner,91.0,398.9m,8.0m,6.9k,0.7%,2.9m,54.9b,United States
5,5therock,91.0,392.8m,1.7m,7.5k,0.3%,982.9k,12.5b,United States
...,...,...,...,...,...,...,...,...,...
196,196frenchmontana,72.0,37.5m,138.2k,160,0.4%,148.9k,22.1m,United States
197,197bmw,79.0,37.5m,213.4k,10.0k,0.3%,104.2k,2.1b,Germany
198,198madhuridixitnene,76.0,37.2m,369.7k,1.6k,0.6%,227.2k,593.7m,India
199,199addisonraee,85.0,36.8m,2.8m,165,1.1%,382.8k,464.0m,NaN
200,200shaymitchell,83.0,36.7m,613.2k,6.5k,0.6%,214.7k,4.0b,United States

In [9]:
# observamos los valores únicos de la columna Channel Info para facilitar su tratamiento
df['Channel Info'].unique()

array(['1cristiano', '2leomessi', '3selenagomez', '4kyliejenner',
       '5therock', '6arianagrande', '7kimkardashian', '8beyonce',
       '9khloekardashian', '10nike', '11kendalljenner', '12justinbieber',
       '13natgeo', '14taylorswift', '15virat.kohli', '16nickiminaj',
       '17kourtneykardash', '18neymarjr', '19mileycyrus', '20katyperry',
       '21zendaya', '22kevinhart4real', '23iamcardib', '24kingjames',
       '25ddlovato', '26badgalriri', '27realmadrid',
       '28chrisbrownofficial', '29champagnepapi', '30theellenshow',
       '31fcbarcelona', '32billieeilish', '33k.mbappe', '34gal_gadot',
       '35vindiesel', '36lalalalisa_m', '37nasa', '38priyankachopra',
       '39Shakira', '40dualipa', '41davidbeckham', '42shraddhakapoor',
       '43nba', '44snoopdogg', '45jennierubyjane', '46aliaabhatt',
       '47narendramodi', '48khaby00', '49gigihadid', '50katrinakaif',
       '51deepikapadukone', '52victoriassecret', '53sooyaaa__',
       '54karimbenzema', '55nehakakkar', '56emmawatson', '57ronaldinho',
       '58roses_are_rosie', '59bts.bighitofficial', '60raffinagita1717',
       '61shawnmendes', '62justintimberlake', '63433',
       '64jacquelienefernandez', '65theweeknd', '66marvel',
       '67beingsalmankhan', '68camila_cabello', '69karolg',
       '70akshaykumar', '71tomholland2013', '72marcelotwelve',
       '73anushkasharma', '74psg', '75anitta', '76willsmith',
       '77iamzlatanibrahimovic', '78maluma', '79milliebobbybrown',
       '80manchesterunited', '81mosalah', '82thv', '83zacefron',
       '84leonardodicaprio', '85sergioramos', '86paulpogba',
       '87bellahadid', '88dishapatani', '89juventus',
       '90whinderssonnunes', '91chrishemsworth', '92paulodybala',
       '939gag', '94blackpinkofficial', '95robertdowneyjr',
       '96michelleobama', '97tatawerneck', '98jokowi', '99ladygaga',
       '100ayutingting92', '101kritisanon', '102adele',
       '103stephencurry30', '104louisvuitton', '105sunnyleone',
       '106prillylatuconsina96', '107cznburak', '108lelepons',
       '109hudabeauty', '110larissamanoela', '111georginagio',
       '112travisscott', '113krisjenner', '114garethbale11', '115gucci',
       '116jamesrodriguez10', '117j.m', '118jbalvin', '119zayn',
       '120vanessahudgens', '121haileybieber', '122vancityreynolds',
       '123harrystyles', '124daddyyankee', '125maisa', '126dovecameron',
       '127luissuarez9', '128natgeotravel', '129jannatzubair29',
       '130worldstar', '131thenotoriousmma', '132varundvn',
       '133buzzfeedtasty', '134badbunnypr', '135mahi7781',
       '136teddysphotos', '137charlidamelio', '138ranveersingh',
       '139hrithikroshan', '140nikefootball', '141houseofhighlights',
       '142prattprattpratt', '143norafatehi', '144kapilsharma',
       '145ruben_onsu', '146brunamarquezine', '147dior', '148rkive',
       '149gusttavolima', '150nickyjampr', '151sachintendulkar',
       '152iamsrk', '1535-Minute Crafts GIRLY', '154parineetichopra',
       '155liverpoolfc', '156princessyahrini', '157fifaworldcup',
       '158andresiniesta8', '159shahidkapoor', '160toni.kr8s',
       '161natashawilona12', '162mrbeast', '163blakelively',
       '164jenniferaniston', '165chrissyteigen', '166britneyspears',
       '167caradelevingne', '168marinaruybarbosa',
       '169mariliamendoncacantora', '170zidane', '171antogriezmann',
       '172katherinelangford', '173wizkhalifa', '174jasonstatham',
       '175eminem', '176jennaortega', '177wesleysafadao',
       '178laudyacynthiabella', '179rashmika_mandanna', '180nancyajram',
       '181anushkasen0408', '182eunwo.o_c', '183gisel_la', '184disney',
       '185hm', '186marvelstudios', '187tigerjackieshroff', '188lunamaya',
       '189kimberly.loaiza', '190djkhaled', '191mercedesbenz',
       '192iambeckyg', '193simonemendes', '194raisa6690',
       '195madisonbeer', '196frenchmontana', '197bmw',
       '198madhuridixitnene', '199addisonraee', '200shaymitchell'],
      dtype=object)

In [10]:
import pandas as pd

# diccionario con los nombres de las channel info
data = {'Channel Info': ['1cristiano', '2leomessi', '3selenagomez', '4kyliejenner',
       '5therock', '6arianagrande', '7kimkardashian', '8beyonce',
       '9khloekardashian', '10nike', '11kendalljenner', '12justinbieber',
       '13natgeo', '14taylorswift', '15virat.kohli', '16nickiminaj',
       '17kourtneykardash', '18neymarjr', '19mileycyrus', '20katyperry',
       '21zendaya', '22kevinhart4real', '23iamcardib', '24kingjames',
       '25ddlovato', '26badgalriri', '27realmadrid',
       '28chrisbrownofficial', '29champagnepapi', '30theellenshow',
       '31fcbarcelona', '32billieeilish', '33k.mbappe', '34gal_gadot',
       '35vindiesel', '36lalalalisa_m', '37nasa', '38priyankachopra',
       '39Shakira', '40dualipa', '41davidbeckham', '42shraddhakapoor',
       '43nba', '44snoopdogg', '45jennierubyjane', '46aliaabhatt',
       '47narendramodi', '48khaby00', '49gigihadid', '50katrinakaif',
       '51deepikapadukone', '52victoriassecret', '53sooyaaa__',
       '54karimbenzema', '55nehakakkar', '56emmawatson', '57ronaldinho',
       '58roses_are_rosie', '59bts.bighitofficial', '60raffinagita1717',
       '61shawnmendes', '62justintimberlake', '63433',
       '64jacquelienefernandez', '65theweeknd', '66marvel',
       '67beingsalmankhan', '68camila_cabello', '69karolg',
       '70akshaykumar', '71tomholland2013', '72marcelotwelve',
       '73anushkasharma', '74psg', '75anitta', '76willsmith',
       '77iamzlatanibrahimovic', '78maluma', '79milliebobbybrown',
       '80manchesterunited', '81mosalah', '82thv', '83zacefron',
       '84leonardodicaprio', '85sergioramos', '86paulpogba',
       '87bellahadid', '88dishapatani', '89juventus',
       '90whinderssonnunes', '91chrishemsworth', '92paulodybala',
       '939gag', '94blackpinkofficial', '95robertdowneyjr',
       '96michelleobama', '97tatawerneck', '98jokowi', '99ladygaga',
       '100ayutingting92', '101kritisanon', '102adele',
       '103stephencurry30', '104louisvuitton', '105sunnyleone',
       '106prillylatuconsina96', '107cznburak', '108lelepons',
       '109hudabeauty', '110larissamanoela', '111georginagio',
       '112travisscott', '113krisjenner', '114garethbale11', '115gucci',
       '116jamesrodriguez10', '117j.m', '118jbalvin', '119zayn',
       '120vanessahudgens', '121haileybieber', '122vancityreynolds',
       '123harrystyles', '124daddyyankee', '125maisa', '126dovecameron',
       '127luissuarez9', '128natgeotravel', '129jannatzubair29',
       '130worldstar', '131thenotoriousmma', '132varundvn',
       '133buzzfeedtasty', '134badbunnypr', '135mahi7781',
       '136teddysphotos', '137charlidamelio', '138ranveersingh',
       '139hrithikroshan', '140nikefootball', '141houseofhighlights',
       '142prattprattpratt', '143norafatehi', '144kapilsharma',
       '145ruben_onsu', '146brunamarquezine', '147dior', '148rkive',
       '149gusttavolima', '150nickyjampr', '151sachintendulkar',
       '152iamsrk', '1535-Minute Crafts GIRLY', '154parineetichopra',
       '155liverpoolfc', '156princessyahrini', '157fifaworldcup',
       '158andresiniesta8', '159shahidkapoor', '160toni.kr8s',
       '161natashawilona12', '162mrbeast', '163blakelively',
       '164jenniferaniston', '165chrissyteigen', '166britneyspears',
       '167caradelevingne', '168marinaruybarbosa',
       '169mariliamendoncacantora', '170zidane', '171antogriezmann',
       '172katherinelangford', '173wizkhalifa', '174jasonstatham',
       '175eminem', '176jennaortega', '177wesleysafadao',
       '178laudyacynthiabella', '179rashmika_mandanna', '180nancyajram',
       '181anushkasen0408', '182eunwo.o_c', '183gisel_la', '184disney',
       '185hm', '186marvelstudios', '187tigerjackieshroff', '188lunamaya',
       '189kimberly.loaiza', '190djkhaled', '191mercedesbenz',
       '192iambeckyg', '193simonemendes', '194raisa6690',
       '195madisonbeer', '196frenchmontana', '197bmw',
       '198madhuridixitnene', '199addisonraee', '200shaymitchell']}

# Eliminamos valores numéricos de la columna Channel Info
df['Channel Info'] = df['Channel Info'].str.replace(r'^\d+', '', regex=True)

print(df)

         Channel Info  Influence Score Followers Avg_Likes  Posts  \
1           cristiano             92.0    612.6m      8.9m   3.6k
2            leomessi             90.0    493.1m      7.6m   1.1k
3         selenagomez             93.0    430.1m      6.7m   2.0k
4         kyliejenner             91.0    398.9m      8.0m   6.9k
5             therock             91.0    392.8m      1.7m   7.5k
..                ...              ...       ...       ...    ...
196     frenchmontana             72.0     37.5m    138.2k    160
197               bmw             79.0     37.5m    213.4k  10.0k
198  madhuridixitnene             76.0     37.2m    369.7k   1.6k
199       addisonraee             85.0     36.8m      2.8m    165
200      shaymitchell             83.0     36.7m    613.2k   6.5k

    60-Day Eng Rate New Post Avg_Likes Total Likes Country Or Region
1              1.1%               6.5m       31.7b             Spain
2              1.0%               4.6m        8.7b               NaN
3              1.0%               4.1m       13.1b     United States
4              0.7%               2.9m       54.9b     United States
5              0.3%             982.9k       12.5b     United States
..              ...                ...         ...               ...
196            0.4%             148.9k       22.1m     United States
197            0.3%             104.2k        2.1b           Germany
198            0.6%             227.2k      593.7m             India
199            1.1%             382.8k      464.0m               NaN
200            0.6%             214.7k        4.0b     United States

[200 rows x 9 columns]

In [11]:
# reparar channel info con números
df['Channel Info'] = df['Channel Info'].str.replace('-Minute Crafts GIRLY', '5-Minute Crafts GIRLY')
df['Channel Info'].replace('', '433', inplace=True)
df['Channel Info'] = df['Channel Info'].str.replace('gag', '9gag')
df['Channel Info'] = df['Channel Info'].str.replace('lady9gaga', 'ladygaga')

df['Channel Info'].unique()

array(['cristiano', 'leomessi', 'selenagomez', 'kyliejenner', 'therock',
       'arianagrande', 'kimkardashian', 'beyonce', 'khloekardashian',
       'nike', 'kendalljenner', 'justinbieber', 'natgeo', 'taylorswift',
       'virat.kohli', 'nickiminaj', 'kourtneykardash', 'neymarjr',
       'mileycyrus', 'katyperry', 'zendaya', 'kevinhart4real',
       'iamcardib', 'kingjames', 'ddlovato', 'badgalriri', 'realmadrid',
       'chrisbrownofficial', 'champagnepapi', 'theellenshow',
       'fcbarcelona', 'billieeilish', 'k.mbappe', 'gal_gadot',
       'vindiesel', 'lalalalisa_m', 'nasa', 'priyankachopra', 'Shakira',
       'dualipa', 'davidbeckham', 'shraddhakapoor', 'nba', 'snoopdogg',
       'jennierubyjane', 'aliaabhatt', 'narendramodi', 'khaby00',
       'gigihadid', 'katrinakaif', 'deepikapadukone', 'victoriassecret',
       'sooyaaa__', 'karimbenzema', 'nehakakkar', 'emmawatson',
       'ronaldinho', 'roses_are_rosie', 'bts.bighitofficial',
       'raffinagita1717', 'shawnmendes', 'justintimberlake', '433',
       'jacquelienefernandez', 'theweeknd', 'marvel', 'beingsalmankhan',
       'camila_cabello', 'karolg', 'akshaykumar', 'tomholland2013',
       'marcelotwelve', 'anushkasharma', 'psg', 'anitta', 'willsmith',
       'iamzlatanibrahimovic', 'maluma', 'milliebobbybrown',
       'manchesterunited', 'mosalah', 'thv', 'zacefron',
       'leonardodicaprio', 'sergioramos', 'paulpogba', 'bellahadid',
       'dishapatani', 'juventus', 'whinderssonnunes', 'chrishemsworth',
       'paulodybala', '9gag', 'blackpinkofficial', 'robertdowneyjr',
       'michelleobama', 'tatawerneck', 'jokowi', 'ladygaga',
       'ayutingting92', 'kritisanon', 'adele', 'stephencurry30',
       'louisvuitton', 'sunnyleone', 'prillylatuconsina96', 'cznburak',
       'lelepons', 'hudabeauty', 'larissamanoela', 'georginagio',
       'travisscott', 'krisjenner', 'garethbale11', 'gucci',
       'jamesrodriguez10', 'j.m', 'jbalvin', 'zayn', 'vanessahudgens',
       'haileybieber', 'vancityreynolds', 'harrystyles', 'daddyyankee',
       'maisa', 'dovecameron', 'luissuarez9', 'natgeotravel',
       'jannatzubair29', 'worldstar', 'thenotoriousmma', 'varundvn',
       'buzzfeedtasty', 'badbunnypr', 'mahi7781', 'teddysphotos',
       'charlidamelio', 'ranveersingh', 'hrithikroshan', 'nikefootball',
       'houseofhighlights', 'prattprattpratt', 'norafatehi',
       'kapilsharma', 'ruben_onsu', 'brunamarquezine', 'dior', 'rkive',
       'gusttavolima', 'nickyjampr', 'sachintendulkar', 'iamsrk',
       '5-Minute Crafts GIRLY', 'parineetichopra', 'liverpoolfc',
       'princessyahrini', 'fifaworldcup', 'andresiniesta8',
       'shahidkapoor', 'toni.kr8s', 'natashawilona12', 'mrbeast',
       'blakelively', 'jenniferaniston', 'chrissyteigen', 'britneyspears',
       'caradelevingne', 'marinaruybarbosa', 'mariliamendoncacantora',
       'zidane', 'antogriezmann', 'katherinelangford', 'wizkhalifa',
       'jasonstatham', 'eminem', 'jennaortega', 'wesleysafadao',
       'laudyacynthiabella', 'rashmika_mandanna', 'nancyajram',
       'anushkasen0408', 'eunwo.o_c', 'gisel_la', 'disney', 'hm',
       'marvelstudios', 'tigerjackieshroff', 'lunamaya',
       'kimberly.loaiza', 'djkhaled', 'mercedesbenz', 'iambeckyg',
       'simonemendes', 'raisa6690', 'madisonbeer', 'frenchmontana', 'bmw',
       'madhuridixitnene', 'addisonraee', 'shaymitchell'], dtype=object)

In [12]:
# nombres de columnas 
df.columns

Index(['Channel Info', 'Influence Score', 'Followers', 'Avg_Likes', 'Posts',
       '60-Day Eng Rate', 'New Post Avg_Likes', 'Total Likes',
       'Country Or Region'],
      dtype='object')

In [13]:
# nombres de columnas como notebook de trabajo principal
df.rename(columns={'Channel Info': 'Usuario', 'Influence Score': 'Puntuación_influence', 'Followers': 'Seguidores', 'Following': 'Siguiendo', 'Avg_Likes': 'Media_likes', 'Posts': 'Posts', '60-Day Eng Rate': 'Tasa_interacción_60d', 'New Post Avg_Likes': 'Media_Likes_Post_Nuevo', 'Total Likes': 'Total_Likes', 'Country Or Region':'País'}, inplace=True)
df

,Usuario,Puntuación_influence,Seguidores,Media_likes,Posts,Tasa_interacción_60d,Media_Likes_Post_Nuevo,Total_Likes,País
1,cristiano,92.0,612.6m,8.9m,3.6k,1.1%,6.5m,31.7b,Spain
2,leomessi,90.0,493.1m,7.6m,1.1k,1.0%,4.6m,8.7b,NaN
3,selenagomez,93.0,430.1m,6.7m,2.0k,1.0%,4.1m,13.1b,United States
4,kyliejenner,91.0,398.9m,8.0m,6.9k,0.7%,2.9m,54.9b,United States
5,therock,91.0,392.8m,1.7m,7.5k,0.3%,982.9k,12.5b,United States
...,...,...,...,...,...,...,...,...,...
196,frenchmontana,72.0,37.5m,138.2k,160,0.4%,148.9k,22.1m,United States
197,bmw,79.0,37.5m,213.4k,10.0k,0.3%,104.2k,2.1b,Germany
198,madhuridixitnene,76.0,37.2m,369.7k,1.6k,0.6%,227.2k,593.7m,India
199,addisonraee,85.0,36.8m,2.8m,165,1.1%,382.8k,464.0m,NaN
200,shaymitchell,83.0,36.7m,613.2k,6.5k,0.6%,214.7k,4.0b,United States

In [14]:
# observamos nulos
df.isnull().sum()

Usuario                    0
Puntuación_influence       0
Seguidores                 0
Media_likes                0
Posts                      0
Tasa_interacción_60d       0
Media_Likes_Post_Nuevo     0
Total_Likes                0
País                      65
dtype: int64

# <CENTER> 2. DATOS FALTANTES

In [15]:
# añadir País a aquellos nulos (más cambio de país a 'cristiano')

df.loc[df['Usuario'] == 'cristiano', 'País'] = 'Portugal'
df.loc[df['Usuario'] == 'leomessi', 'País'] = 'Argentina'
df.loc[df['Usuario'] == 'virat.kohli', 'País'] = 'India'
df.loc[df['Usuario'] == 'mileycyrus', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'katyperry', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'kingjames', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'fcbarcelona', 'País'] = 'España'
df.loc[df['Usuario'] == 'billieeilish', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'lalalalisa_m', 'País'] = 'Tailandia'
df.loc[df['Usuario'] == 'Shakira', 'País'] = 'Colombia'
df.loc[df['Usuario'] == 'snoopdogg', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'shraddhakapoor', 'País'] = 'India'
df.loc[df['Usuario'] == 'k.mbappe', 'País'] = 'Francia'
df.loc[df['Usuario'] == 'jennierubyjane', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'tomholland2013', 'País'] = 'Reino Unido'
df.loc[df['Usuario'] == 'sooyaaa__', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'akshaykumar', 'País'] = 'India'
df.loc[df['Usuario'] == 'roses_are_rosie', 'País'] = 'New Zealand'
df.loc[df['Usuario'] == 'anushkasharma', 'País'] = 'India'
df.loc[df['Usuario'] == 'iamzlatanibrahimovic', 'País'] = 'Sweden'
df.loc[df['Usuario'] == 'leonardodicaprio', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'juventus', 'País'] = 'Italia'
df.loc[df['Usuario'] == 'sunnyleone', 'País'] = 'Canada'
df.loc[df['Usuario'] == 'sergioramos', 'País'] = 'España'
df.loc[df['Usuario'] == 'jbalvin', 'País'] = 'Colombia'
df.loc[df['Usuario'] == 'mosalah', 'País'] = 'Egypt'
df.loc[df['Usuario'] == 'michelleobama', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'thv', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'charlidamelio', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'paulodybala', 'País'] = 'Argentina'
df.loc[df['Usuario'] == 'blackpinkofficial', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'garethbale11', 'País'] = 'Reino Unido'
df.loc[df['Usuario'] == 'jokowi', 'País'] = 'Indonesia'
df.loc[df['Usuario'] == 'haileybieber', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'stephencurry30', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'vancityreynolds', 'País'] = 'Canada'
df.loc[df['Usuario'] == 'luissuarez9', 'País'] = 'Uruguay'
df.loc[df['Usuario'] == 'jannatzubair29', 'País'] = 'India'
df.loc[df['Usuario'] == 'kapilsharma', 'País'] = 'India'
df.loc[df['Usuario'] == 'badbunnypr', 'País'] = 'Puerto Rico'
df.loc[df['Usuario'] == 'j.m', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'theweeknd', 'País'] = 'Canada'
df.loc[df['Usuario'] == 'dior', 'País'] = 'Francia'
df.loc[df['Usuario'] == 'jenniferaniston', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'addisonraee', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'natashawilona12', 'País'] = 'Indonesia'
df.loc[df['Usuario'] == 'mahi7781', 'País'] = 'India'
df.loc[df['Usuario'] == 'georginagio', 'País'] = 'España'
df.loc[df['Usuario'] == 'cznburak', 'País'] = 'Turquía'
df.loc[df['Usuario'] == 'anushkasen0408', 'País'] = 'India'
df.loc[df['Usuario'] == 'prattprattpratt', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'marvelstudios', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'wesleysafadao', 'País'] = 'Brasil'
df.loc[df['Usuario'] == 'parineetichopra', 'País'] = 'India'
df.loc[df['Usuario'] == 'rkive', 'País'] = 'Corea del Sur'
df.loc[df['Usuario'] == 'gisel_la', 'País'] = 'Indonesia'
df.loc[df['Usuario'] == 'colesprouse', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'shahidkapoor', 'País'] = 'India'
df.loc[df['Usuario'] == 'sachintendulkar', 'País'] = 'India'
df.loc[df['Usuario'] == 'lunamaya', 'País'] = 'Indonesia'
df.loc[df['Usuario'] == 'toni.kr8s', 'País'] = 'Alemania'
df.loc[df['Usuario'] == 'paollaoliveirareal', 'País'] = 'Brasil'
df.loc[df['Usuario'] == 'adidasoriginals', 'País'] = 'Alemania'
df.loc[df['Usuario'] == 'khaby00', 'País'] = 'Italia'
df.loc[df['Usuario'] == 'houseofhighlights', 'País'] = 'Estados Unidos'
df.loc[df['Usuario'] == 'fifaworldcup', 'País'] = 'Suiza'
df.loc[df['Usuario'] == 'katherinelangford', 'País'] = 'Australia'
df.loc[df['Usuario'] == 'rashmika_mandanna', 'País'] = 'India'
df.loc[df['Usuario'] == 'eunwo.o_c', 'País'] = 'Corea del Sur'

In [16]:
# vemos países únicos
df['País'].unique()

array(['Portugal', 'Argentina', 'United States', 'Canada', 'India',
       'Brazil', 'Estados Unidos', 'Spain', 'Netherlands', 'España',
       'Francia', 'Tailandia', 'Colombia', 'United Kingdom',
       'Corea del Sur', 'Italia', 'New Zealand', 'Uruguay', 'Indonesia',
       'Turkey', 'Reino Unido', 'France', 'Sweden', 'Egypt', 'Australia',
       'Turquía', 'Italy', 'Puerto Rico', 'Switzerland', "Côte d'Ivoire",
       'Anguilla', 'Suiza', 'Alemania', 'China', 'Brasil', 'Mexico',
       'British Virgin Islands', 'Germany'], dtype=object)

In [17]:
# cambiar país Unted States por Estados Unidos

df['País'] = df['País'].str.replace('United States', 'Estados Unidos')
df['País'] = df['País'].str.replace('United Kingdom', 'Reino Unido')
df['País'] = df['País'].str.replace('South Korea', 'Corea del Sur')
df['País'] = df['País'].str.replace('Turkey', 'Turquía')
df['País'] = df['País'].str.replace('Brazil', 'Brasil')
df['País'] = df['País'].str.replace('France', 'Francia')
df['País'] = df['País'].str.replace('Spain', 'España')
df['País'] = df['País'].str.replace('Netherlands', 'Holanda')
df['País'] = df['País'].str.replace('New Zealand', 'Nueva Zelanda')
df['País'] = df['País'].str.replace('Sweden', 'Suecia')
df['País'] = df['País'].str.replace('Egypt', 'Egipto')
df['País'] = df['País'].str.replace('Italy', 'Italia')
df['País'] = df['País'].str.replace('Switzerland', 'Suiza')
df['País'] = df['País'].str.replace("Côte d'Ivoire", 'Costa de Marfil')
df['País'] = df['País'].str.replace('British Virgin Islands', 'Islas Vírgenes Británicas')
df['País'] = df['País'].str.replace('Germany', 'Alemania')

In [18]:
# comprueba que no queda ningún país en inglés
df['País'].unique()

array(['Portugal', 'Argentina', 'Estados Unidos', 'Canada', 'India',
       'Brasil', 'España', 'Holanda', 'Francia', 'Tailandia', 'Colombia',
       'Reino Unido', 'Corea del Sur', 'Italia', 'Nueva Zelanda',
       'Uruguay', 'Indonesia', 'Turquía', 'Suecia', 'Egipto', 'Australia',
       'Puerto Rico', 'Suiza', 'Costa de Marfil', 'Anguilla', 'Alemania',
       'China', 'Mexico', 'Islas Vírgenes Británicas'], dtype=object)

In [19]:
# ver channel_info donde country es Côte d'Ivoire
print(df[df['País'] == "Costa de Marfil"]['Usuario'])

139    hrithikroshan
Name: Usuario, dtype: object

In [20]:
# es de India y no de Costa de Marfil
df.loc[df['Usuario'] == 'hrithikroshan', 'País'] = 'India'

In [21]:
# añadimos columna con el idioma con el nombre de 'channel_main_language'
df['Idioma_principal'] = None

In [22]:
# comprobamos 
df.columns

Index(['Usuario', 'Puntuación_influence', 'Seguidores', 'Media_likes', 'Posts',
       'Tasa_interacción_60d', 'Media_Likes_Post_Nuevo', 'Total_Likes', 'País',
       'Idioma_principal'],
      dtype='object')

In [23]:
# añadir manualmente el Idioma_principal de cada fila


df.loc[df['Usuario'] == 'cristiano', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'leomessi', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'selenagomez', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kyliejenner', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'therock', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'arianagrande', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kimkardashian', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'beyonce', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'khloekardashian', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nike', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kendalljenner', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'justinbieber', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'natgeo', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'taylorswift', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'virat.kohli', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nickiminaj', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kourtneykardash', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'neymarjr', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'mileycyrus', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'katyperry', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'zendaya', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kevinhart4real', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'iamcardib', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kingjames', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'ddlovato', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'badgalriri', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'realmadrid', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'chrisbrownofficial', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'champagnepapi', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'theellenshow', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'fcbarcelona', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'billieeilish', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'k.mbappe', 'Idioma_principal'] = 'Francés'
df.loc[df['Usuario'] == 'gal_gadot', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'vindiesel', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'lalalalisa_m', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nasa', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'priyankachopra', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'Shakira', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'dualipa', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'davidbeckham', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'shraddhakapoor', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nba', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'snoopdogg', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jennierubyjane', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'aliaabhatt', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'narendramodi', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'khaby00', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'gigihadid', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'katrinakaif', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'deepikapadukone', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'victoriassecret', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'sooyaaa__', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'karimbenzema', 'Idioma_principal'] = 'Francés'
df.loc[df['Usuario'] == 'nehakakkar', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'emmawatson', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'ronaldinho', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'roses_are_rosie', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'bts.bighitofficial', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'raffinagita1717', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'shawnmendes', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'justintimberlake', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == '433', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jacquelienefernandez', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'theweeknd', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'marvel', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'beingsalmankhan', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'camila_cabello', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'karolg', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'akshaykumar', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'tomholland2013', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'marcelotwelve', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'anushkasharma', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'psg', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'anitta', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'willsmith', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'iamzlatanibrahimovic', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'maluma', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'milliebobbybrown', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'manchesterunited', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'mosalah', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'thv', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'zacefron', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'leonardodicaprio', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'sergioramos', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'paulpogba', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'bellahadid', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'dishapatani', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'juventus', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'whinderssonnunes', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'chrishemsworth', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'paulodybala', 'Idioma_principal'] = 'Italiano'
df.loc[df['Usuario'] == '9gag', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'blackpinkofficial', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'robertdowneyjr', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'michelleobama', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'tatawerneck', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'jokowi', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'ladygaga', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'ayutingting92', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'kritisanon', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'adele', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'stephencurry30', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'louisvuitton', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'sunnyleone', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'prillylatuconsina96', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'cznburak', 'Idioma_principal'] = 'Turco'
df.loc[df['Usuario'] == 'lelepons', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'hudabeauty', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'larissamanoela', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'georginagio', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'travisscott', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'krisjenner', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'garethbale11', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'gucci', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jamesrodriguez10', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'j.m', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jbalvin', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'zayn', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'vanessahudgens', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'haileybieber', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'vancityreynolds', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'harrystyles', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'daddyyankee', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'maisa', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'dovecameron', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'luissuarez9', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'natgeotravel', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jannatzubair29', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'worldstar', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'thenotoriousmma', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'varundvn', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'buzzfeedtasty', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'badbunnypr', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'mahi7781', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'teddysphotos', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'charlidamelio', 'Idioma_principal'] = 'Inglés'  
df.loc[df['Usuario'] == 'ranveersingh', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'hrithikroshan', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nikefootball', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'houseofhighlights', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'prattprattpratt', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'norafatehi', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'kapilsharma', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'ruben_onsu', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'brunamarquezine', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'dior', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'rkive', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'gusttavolima', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'nickyjampr', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'sachintendulkar', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'iamsrk', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == '5-Minute Crafts GIRLY', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'parineetichopra', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'liverpoolfc', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'princessyahrini', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'fifaworldcup', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'andresiniesta8', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'shahidkapoor', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'toni.kr8s', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'natashawilona12', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'mrbeast', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'blakelively', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jenniferaniston', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'chrissyteigen', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'britneyspears', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'caradelevingne', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'marinaruybarbosa', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'mariliamendoncacantora', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'zidane', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'antogriezmann', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'katherinelangford', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'wizkhalifa', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jasonstatham', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'eminem', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'jennaortega', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'wesleysafadao', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'laudyacynthiabella', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'rashmika_mandanna', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'nancyajram', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'anushkasen0408', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'eunwo.o_c', 'Idioma_principal'] = 'Coreano'
df.loc[df['Usuario'] == 'gisel_la', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'disney', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'hm', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'marvelstudios', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'tigerjackieshroff', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'lunamaya', 'Idioma_principal'] = 'Indonesio'
df.loc[df['Usuario'] == 'kimberly.loaiza', 'Idioma_principal'] = 'Español'
df.loc[df['Usuario'] == 'djkhaled', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'mercedesbenz', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'iambeckyg', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'simonemendes', 'Idioma_principal'] = 'Portugés'
df.loc[df['Usuario'] == 'raisa6690', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'madisonbeer', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'frenchmontana', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'bmw', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'madhuridixitnene', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'addisonraee', 'Idioma_principal'] = 'Inglés'
df.loc[df['Usuario'] == 'shaymitchell', 'Idioma_principal'] = 'Inglés'

In [24]:
# observamos que no están bien escritos
df['Idioma_principal'].unique()

array(['Inglés', 'Español', 'Portugés', 'Francés', 'Indonesio',
       'Italiano', 'Turco', 'Coreano'], dtype=object)

In [25]:
# vemos que no hay nulos antes de guardar 
df.isnull().sum()

Usuario                   0
Puntuación_influence      0
Seguidores                0
Media_likes               0
Posts                     0
Tasa_interacción_60d      0
Media_Likes_Post_Nuevo    0
Total_Likes               0
País                      0
Idioma_principal          0
dtype: int64

# <CENTER> 3. GUARDAMOS PARA COMENZAR A TRABAJAR

In [27]:
# creación de csv listo para comenzar
df.to_csv('dataV2.csv', index=False)